apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: todo-app
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki-service:3100
        jsonData:
          derivedFields:
            - name: TraceID
              matcherRegex: '"trace_id":"([a-f0-9]+)"'
              datasourceUid: jaeger
              url: '$${__value.raw}'
              urlDisplayLabel: 'Open Trace'
      - name: Jaeger
        uid: jaeger
        type: jaeger
        access: proxy
        url: http://jaeger-service:16686
  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: 'Default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
