apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: todo-app
spec:
  selector:
    app: loki
  ports:
  - port: 3100
    targetPort: 3100
    protocol: TCP
    name: http
  type: ClusterIP
