apiVersion: v1
kind: Service
metadata:
  name: redis-task
  namespace: todo-app
spec:
  selector:
    app: redis-task
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  type: ClusterIP
