apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: todo-app
type: Opaque
stringData:
  # Neon connection string
  DATABASE_URL: postgresql://neondb_owner:npg_4xr1XykGAfZC@ep-wild-cloud-aliinkug-pooler.c-3.eu-central-1.aws.neon.tech/todo_db?sslmode=require&channel_binding=require
