apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: todo-app
type: Opaque
stringData:
  # Renseigner vos vraies valeurs avant déploiement
  DATABASE_URL: postgresql://neondb_owner:npg_4xr1XykGAfZC@ep-wild-cloud-aliinkug-pooler.c-3.eu-central-1.aws.neon.tech/todo_db?sslmode=require&channel_binding=require
  AUTH_DATABASE_URL: postgresql://neondb_owner:npg_4xr1XykGAfZC@ep-wild-cloud-aliinkug-pooler.c-3.eu-central-1.aws.neon.tech/auth_db?sslmode=require&channel_binding=require
  JWT_SECRET: b2c679e56d143da88c00ba285d7d2a81f119474831600734a821ce8340be6923
