name: CI
on: [push, pull_request]
env:
  FORCE_COLOR: 2

jobs:
  ci-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 20
          cache: npm
      - run: npm ci --ignore-scripts

      - name: Format check
        run: npm run format-check
        working-directory: apps/backend

      - name: Tests
        run: npm test
        working-directory: apps/backend

  ci-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 20
          cache: npm

      - run: npm ci --ignore-scripts

      - name: Format check
        run: npm run format-check
        working-directory: apps/client

      - name: Lint
        run: npm run lint
        working-directory: apps/client

      - name: Build
        run: npm run build
        working-directory: apps/client

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
